### ISSUE TITLE
Make server bar buttons MS store sidebar styles

### ISSUE THREAD

**Issue by Josh65-2201** [Josh-65/Discord-Win11-theme#30]
**Describe the solution you'd like**  
![image](https://user-images.githubusercontent.com/26977075/149687823-51bb4e3b-d32a-426e-8c63-9aa2101f1e56.png)

Current issues:
Hover pill animation appears
Unread dot doesnt show when hovered

**Comment by Josh-65** [comment]
Current issues:
Hover pill animation appears
Unread dot doesnt show when hovered
